id: ID7435242
default_language: fr
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:28:30.808237
last_modified: 2023-01-04 11:28:30.808255
source_metadata:
  collections:
  - Alak Zenkar Rinpoche
  - Works of Tibetan Masters
bases:
  7B36:
    title: A Brief Presentation of the Nine Vehicles
    base_file: 7B36.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
